export { default as setVar } from './setVar'
export { default as setColor } from './setColor'
export { default as sticky } from './sticky'
export { default as ripple } from './ripple'
export { default as clipboard } from './clipboard'
